### PR TITLE
Add ingestion sdk

### PR DESCRIPTION
**Pull request by ghost**
(This replaces PR #6 - the only change, as of the time of opening the PR, is the branch name)

## Description

Adds a new SDK client type (along android & JVM), namely a client meant for use in the ingestion pipeline (the component previously known as "the broker").

## Motivation and Context

In the data ingestion pipeline, the SDK is used through a Kotlin library that handles only validation and the actual upload. The authentication and authorization against the Data4Life platform is handled by other components of the pipeline. Hence, there is the need for a new client type that does handle the OAuth flow, but instead simply uses a valid access token that is passed by the code using the SDK. 

## How is it being implemented?

The new client is put in its own module and parallels the JVM client quite closely, with the exception of the OAuth handling. The aim was to provide this new functionality with a minimum of disturbance to the existing core SDK modules. Accordingly, changes have been implemented in the new module wherever possible. However, minor changes where needed in the crypto module (extended key handling) as well as the core module (adapt ApiService to allow access to handling).

## How Has This Been Tested?

* Unit tests have been added for all new functionality.
* Successful uploading to Data4Life platform has been verified using the ingestion library (using the SDK from this branch) and a "mock ingestion pipeline" set-up.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [ ] I have updated the changelog accordingly.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by me-d4l** [comment]
@wmontwe This is the new PR with branch name following the new convention (note, however, that there are still open comments in the old PR). I did not update the CHANGELOG since I was not sure of what the conventions are, e.g. whether it should be updated with each PR.

@sebastianwoinar FYI.

**Comment by wmontwe** [comment]
> @wmontwe This is the new PR with branch name following the new convention (BTW, open comments from the old PR are, quite helpfully, also shown here). I did not update the CHANGELOG since I was not sure of what the conventions are, e.g. whether it should be updated with each PR.

the changelog is updated with every pull-request

**Comment by sebastianwoinar** [comment]
@wmontwe what else, do you think must be done, to merge this?
We were able to upload a document using the "ingestion-sdk" 💪🏽

**Comment by me-d4l** [comment]
@wmontwe Updated the CHANGELOG, putting the new change in the entry for the unreleased version.

**Review by wmontwe — APPROVED** [review]
Looks good 👍 

Just be aware that we extend the SDKs API to support Custom Data alongside FHIR, which will come with an additional set of API calls.

**Pull request merged**
